#!/usr/bin/env python2

import argparse, shutil, os
from tools import pkg as pkg_module

class Arguments:
	def __init__( self ):
		self.parser = argparse.ArgumentParser()
		
		self.parser.add_argument( 'package_names', metavar='PACKAGE', type=str, nargs='*',
		                          help='packages to remove' )
		
		self.args = self.parser.parse_args()
	
	def handle( self ):
		to_purge = []
		for package_name in self.args.package_names:
			to_purge.append( pkg_module.Package(package_name).highest_version() )
		
		print 'The following packages and sources will be removed:'
		for version in to_purge:
			print version.package.name + ' - ' + version.string
		
		for version in to_purge:
			if os.path.isdir( version.system_path() ):
				shutil.rmtree( version.system_path() )
			
			if os.path.isdir( version.path() ):
				shutil.rmtree( version.path() )

args = Arguments()
args.handle()

