#!/usr/bin/env python2

import argparse
from tools import pkg as pkg_module

class Arguments:
	def __init__( self ):
		self.parser = argparse.ArgumentParser()

		self.parser.add_argument( 'package_names', metavar='LIBRARY', type=str, nargs='*',
		                          help='packages to download' )
		
		self.parser.add_argument( '--download', action='store_true',
		                          help='ensures that packages get downloaded before building' )
		
		self.args = self.parser.parse_args()
		
	def handle( self ):
		versions = []
		
		for package_name in self.args.package_names:
				versions.append( pkg_module.Package(package_name).highest_version() )
		
		if( self.args.download ):
			for version in versions:
				version.download()
		
		for version in versions:
			version.build()

args = Arguments()
args.handle()
