#!/usr/bin/env python2

import argparse
from tools import pkg as pkg_module

class Arguments:
	def __init__( self ):
		self.parser = argparse.ArgumentParser()
		
		self.parser.add_argument( 'package_names', metavar='LIBRARY', type=str, nargs='*',
		                          help='packages to download' )
		
		self.args = self.parser.parse_args()
	
	def handle( self ):
		to_download = []
		for package_name in self.args.package_names:
			to_download.append( pkg_module.Package(package_name).highest_version() )
		
		print 'The following package sources will be installed:'
		for version in to_download:
			print version.package.name + ' - ' + version.string
		
		for version in to_download:
			version.download()

args = Arguments()
args.handle()

