#!/usr/bin/env python2

import argparse
import os
import subprocess
import sys
import fnmatch
import glob
from tools import pkg as pkg_module

search_paths = pkg_module.lib_dir.config_search_paths()

env = os.environ.copy()
# We have to preserve PKG_CONFIG_PATH values, but our own
# have precedence
#if hasattr( env, 'PKG_CONFIG_PATH' ):
#	search_paths.append( env['PKG_CONFIG_PATH'] )

env['PKG_CONFIG_LIBDIR'] = os.pathsep.join( search_paths )

command = [ 'pkg-config' ] + sys.argv[1:]

sys.exit( subprocess.call(command, env=env) )

